[Shell] <feat> #2 added Dockerfile
pretraining/template pull request #20
Opened 2021-03-03 09:50 UTC by Ronalmoo

#2 

- dockerfile 작성

2021-03-03 15:59 UTC, ssaru commented on docker/Dockerfile
> +FROM nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu${UBUNTU_VERSION} as base
base image는 이름 전체를 `ARGS`로 받아서 처리하기로 하지 않았었나요?

@aisolab

2021-03-03 15:59 UTC, ssaru commented on docker/Dockerfile
> +ARG PYTHON_VERSION=3.7.9
default python version은 3.7.9로 해도 상관없을까요?
@aisolab

2021-03-03 16:04 UTC, ssaru commented on docker/Dockerfile
> +RUN apt-get update && apt-get install -y \
`apt-get install`로 다수의 package를 설치하는데, 꼭 필요한 패키지만 설치하는 이유가 있으신지 궁금합니다.
대표적인 예로 컨테이너는 non-root가 권장사항인데 `sudo`를 설치하는 이유가 있으신지요?

2021-03-03 16:06 UTC, ssaru commented on docker/Dockerfile
> +    apt-get clean
여기도 open-jdk가 필요한 이유가 무엇일까요?

그리고 이건 마이너하지만, `RUN apt-get install` 구문이 상단에도 있는데,
`RUN` 키워드를 쓰면, 레이어가 나눠져서 Docker Image용량이 커집니다. 하나로 합치면 더 좋을 것 같습니다.

2021-03-03 16:06 UTC, ssaru commented on docker/Dockerfile
> +RUN adduser ${USER} sudo
sudo권한을 준 USER와 그냥 root와는 어떤 차이일까요?

2021-03-03 16:07 UTC, ssaru commented on docker/Dockerfile
> +    pip install --no-cache-dir notebook==5.* pyspark==${SPARK_VER} spylon-kernel==0.4.* && \
requirements.txt로도 설치할 수 있을 것 같은데요, notebook과 pyspark 및 기타 파이썬 패키지를 dockerfile내에서 설치하는 이유가 따로 있으실까요?

2021-03-03 16:08 UTC, ssaru commented on docker/Dockerfile
> +RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc
하나의 구문으로 합칠 수 있다면 더 좋을 것 같은데요.
필요성을 못느끼시면 안하셔도 될 것 같습니다.

2021-03-03 16:09 UTC, ssaru commented on docker/Dockerfile
> +USER root
이렇게하면 위에서 USER 다 셋팅하고, 정작 root권한으로 쓰는거 아닌가요?

2021-03-03 16:12 UTC, ssaru requested changes
@Ronalmoo 코멘트 완료했습니다.
Dockerfile을 추가하셨는데, Dockerfile을 추가하셨다면 이를 빌드하고 사용하는 방법까지 `Makefile`에 서술해서 올려주시면 리뷰어들이 테스트하기 더 용이할 것 같습니다.

@aisolab 보섭님, 코멘트 확인하고 의견 부탁드리겠습니다.

2021-03-04 01:43 UTC, Ronalmoo commented on docker/Dockerfile
> +    pip install --no-cache-dir notebook==5.* pyspark==${SPARK_VER} spylon-kernel==0.4.* && \
아 73line은 실수로 넣었습니다.  삭제하겠습니다.

2021-03-04 01:51 UTC, Ronalmoo commented on docker/Dockerfile
> +FROM nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu${UBUNTU_VERSION} as base
아 맞습니다 수정하겠습니다.

2021-03-04 02:05 UTC, aisolab requested changes

2021-03-04 04:55 UTC, Ronalmoo commented on docker/Dockerfile
> +    apt-get clean
네 알겠습니다. Run 키워드 중복 사용을 줄여서 레이어 수를 줄이겠습니다.

2021-03-04 14:45 UTC, Ronalmoo commented on docker/Dockerfile
> +RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc
네 알겠습니다.

2021-03-04 14:46 UTC, Ronalmoo commented on docker/Dockerfile
> +    python -m spylon_kernel install --sys-prefix
네 필요한 패키지 최소로 하겠습니다.

2021-03-04 15:36 UTC, Ronalmoo commented on docker/Dockerfile
> +RUN apt-get update && apt-get install -y \
일단 넣고 필요없으면 소거하는 방식으로 하려했는데 필요한 패키지 추려서 설치하겠습니다.

2021-03-04 15:37 UTC, Ronalmoo commented on docker/Dockerfile
> +FROM nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu${UBUNTU_VERSION} as base
네 이미지 이름도 ARG로 받겠습니다.

2021-03-05 06:34 UTC, Ronalmoo reviewed
수정하였습니다.

2021-03-05 06:54 UTC, ssaru commented on docker/Dockerfile
> +FROM ${BASE_IMAGE}${UBUNTU_VERSION} as base
보섭님은 이걸 말씀하신겁니다.

```suggestion
FROM ${BASE_IMAGE} as base
```

2021-03-05 06:55 UTC, ssaru commented on docker/Dockerfile
> +    sudo \
`sudo`는 뺍시다
```suggestion
```

2021-03-05 06:56 UTC, ssaru commented on docker/Dockerfile
> +    zsh \
`zsh` shell도 굳이 필요 없을 것 같습니다.
```suggestion
```

2021-03-05 06:57 UTC, ssaru commented on docker/Dockerfile
> +RUN adduser ${USER} sudo
이렇게만 해도 되지 않나요?

```suggestion
RUN adduser ${USER}
```

2021-03-05 06:58 UTC, ssaru reviewed
@Ronalmoo 리뷰했습니다.

cc. @aisolab

2021-03-05 08:54 UTC, aisolab commented on docker/Dockerfile
> +FROM ${BASE_IMAGE} as base
`as base`는 무슨 문법일까요? 궁금해서 여쭤봅니다.

cc: @ssaru

2021-03-05 09:18 UTC, Ronalmoo commented on docker/Dockerfile
> +FROM ${BASE_IMAGE} as base
참고한 연구실 이미지인데 base image라고 alias한 것이고, 특별한 용도나 의미하는 바는 없는 것 같습니다.

2021-03-05 12:52 UTC, ssaru commented on docker/Dockerfile
> +FROM ${BASE_IMAGE} as base
그냥 `import numpy as np`와 같은걸 겁니다.
근데, 굳이 `as base`를 써야하는지에 대해서는 잘 모르겠네요.

2021-03-05 13:44 UTC, Ronalmoo commented on docker/Dockerfile
> +FROM ${BASE_IMAGE} as base
alias 삭제 하겠습니다.

2021-03-10 00:52 UTC, closed without merging