Feature/#37
pretraining/template pull request #38
Opened 2021-03-11 12:20 UTC by aisolab

#37 

- `Dockerfile`, `build-image.sh` 추가
- `pyproject.toml`을 `setup.cfg`로 교체
  - 이 과정에서 `black` 대신 `brunette`를 사용함.
-  `Makefile` 추가
  - 이 과정에서 `requirements.txt`를 삭제, (`make set-test` command가 대체)
- `README.md` 수정
  - `make` 관련 command를 사용하는 방식을 안내  

cc: @pretraining/authors

2021-03-11 14:08 UTC, alxiom commented on tests/test_dummy.py
> +from src.example import dummy
이 라인을 통해 유추할 수 있는 것은, "소스코드를 `src` 디렉토리 예하에 위치하도록 하는 한다" 로 이해하면 될까요?

2021-03-11 14:08 UTC, alxiom commented on setup.cfg
> +disable = C0330, C0326, C0114, C0115, C0116
C0330, C0326 도 주석을 부탁합니다~

2021-03-11 14:10 UTC, alxiom commented on setup.cfg
> +extend-ignore = E203, W503
E203: Whitespace before ':' 
W503: Line break occurred before a binary operator

위 2개는 ignore 하지 않는게 어떨까요?

2021-03-11 14:11 UTC, alxiom commented on .pre-commit-config.yaml
> +  - repo: local
로컬 설치가 필요한 `pylint`와 `pytest`에 대한 가이드가 어딘가에 필요할 것 같습니다
Dockerfile에 pre-commit과 함께 추가하는 것도 좋을 것 같고요

2021-03-11 14:13 UTC, alxiom commented on sh/build-image.sh
> +cd ${SCRIPT_DIR_PATH}/..
Dockerfile 경로를 확인해봐야 할 것 같아요
`docker/Dockerfile` 로 기억하고 있습니다

2021-03-11 14:39 UTC, aisolab commented on tests/test_dummy.py
> +from src.example import dummy
@alxiom 네네 의도하였습니다!

2021-03-11 14:40 UTC, aisolab commented on setup.cfg
> +disable = C0330, C0326, C0114, C0115, C0116
@alxiom disable에서 제외해달라는 말씀이신거죠? 일단 `pylint`의 disable 항목에 `C0330`, C0326`이 들어가있는 이유는 아래에 기인합니다. 한번 확인부탁드려요.

https://black.readthedocs.io/en/stable/compatible_configs.html

2021-03-11 14:41 UTC, aisolab commented on setup.cfg
> +extend-ignore = E203, W503
@alxiom 요것도 `black` compatible에 기인합니다. 한번 같이 논의해보시죠.

https://black.readthedocs.io/en/stable/compatible_configs.html

2021-03-11 14:42 UTC, aisolab commented on sh/build-image.sh
> +    -f docker/Dockerfile \
@alxiom 여기서 `docker/Dockerfile`로 파일의 경로를 명시하고 있습니다.

2021-03-11 14:43 UTC, aisolab commented on .pre-commit-config.yaml
> +  - repo: local
@alxiom 일단 `pylint`와 `pytest`에 대한 부분을 local로 동작해야하므로 `make set-git` command를 실행하면 local에 설치하게끔 되어있긴합니다.

2021-03-11 14:44 UTC, aisolab commented on .pre-commit-config.yaml
> +  - repo: local
https://github.com/pretraining/template/blob/5971019874f5d9d31db40e84e51e6e2bf9d93471/Makefile#L5

2021-03-11 15:08 UTC, alxiom commented on setup.cfg
> +disable = C0330, C0326, C0114, C0115, C0116
아아 제외하는게 아니라 ㅋㅋ 설명을 주석으로 부탁드린다는 뜻이었슴다 ㅋ

2021-03-11 15:08 UTC, alxiom commented on setup.cfg
> +extend-ignore = E203, W503
아하 이런이런 야레야레

2021-03-11 15:09 UTC, alxiom commented on .pre-commit-config.yaml
> +  - repo: local
오우야 있었군요

2021-03-11 15:09 UTC, alxiom commented on sh/build-image.sh
> +    -f docker/Dockerfile \
아앗 여깄었잖아여?!

2021-03-12 00:43 UTC, bzantium approved these changes
Makefile과 pre-commit-config의 환상적인 조합.

2021-03-12 02:26 UTC, dreamgonfly commented
> pyproject.toml을 setup.cfg로 교체
이 과정에서 black 대신 brunette를 사용함.

preferred format인 toml 대신 setup.cfg를 하신 이유가 혹시 무엇일까요?

2021-03-12 02:36 UTC, dreamgonfly reviewed
몇가지 코멘트 남겼습니다!

그리고 src 디렉토리에 대해서도 미팅에서 얘기 나누면 좋을 것 같습니다.
제 생각에 파이썬 프로젝트에서 src라는 이름을 쓰는 것은 일반적이지는 않는 것 같습니다.
java 등 언어에서 src라는 이름을 쓰는 가장 큰 이유는 compiled된 결과물이랑 구분하기 위해서인데 파이썬은 그런 구분이 없어서요.

2021-03-12 02:36 UTC, dreamgonfly commented on tests/test_dummy.py
> +    assert dummy
```suggestion
    assert dummy()
```

2021-03-12 02:36 UTC, dreamgonfly commented on requirements.txt
> -pre-commit>=2.10.1
requirements.txt 는 파이썬의 convention으로 알고 있고 requirements.txt를 보고 dependency check 등을 자동으로 하기도 하는데  미팅에서 얘기 나누면 좋을 것 같아요

2021-03-12 02:55 UTC, aisolab commented
> > pyproject.toml을 setup.cfg로 교체
> > 이 과정에서 black 대신 brunette를 사용함.
> 
> preferred format인 toml 대신 setup.cfg를 하신 이유가 혹시 무엇일까요? toml로는 할 수 없는 기능이 있는지 궁금합니다!

2021-03-12 02:55 UTC, aisolab commented
> > > pyproject.toml을 setup.cfg로 교체
> > > 이 과정에서 black 대신 brunette를 사용함.
> > 
> > 
> > preferred format인 toml 대신 setup.cfg를 하신 이유가 혹시 무엇일까요? toml로는 할 수 없는 기능이 있는지 궁금합니다!

https://github.com/pretraining/template/issues/34 에 적혀있습니다!

2021-03-12 05:02 UTC, ssaru commented on .pre-commit-config.yaml
> +      - id: flake8
indent가 하나 더 들어가있는 것 같은데요. 이 부분은 의도하신걸까요?

2021-03-12 05:05 UTC, ssaru commented on .pre-commit-config.yaml
> +  - repo: local
제가 기억하고있기로는 pylint와 pytest를 local에서 동작시킬 때, `pre-commit-config.yaml`에 해당 레포 주소나 이름을 명시해주면, 별도의 설치 필요 없이 온라인에서 pull해서 인스턴스하게 동작한다고 들었던 것 같은데,,, 제가 뭔가 놓치고있는게 있을까요?

아니면,,, 그게 있더라도, 별도로 local에서 동작시켜볼 수 있도록 가이드를 주자는 말씀이실까요?

2021-03-12 06:18 UTC, ssaru commented on setup.cfg
> +disable = C0330, C0326, C0114, C0115, C0116
이걸 말씀드리는게 아닌가 싶습니다.

```suggestion
disable = C0330, C0326, C0114, C0115, C0116
# C0330: Wrong hanging indentation before block (add 4 spaces)
# C0326: bad-whitespace
# C0114: missing-class-docstring
# C0116: missing-function-docstring
```

2021-03-12 06:19 UTC, ssaru commented on setup.cfg
> +extend-ignore = E203, W503
```suggestion
extend-ignore = E203, W503
#refers: https://black.readthedocs.io/en/stable/compatible_configs.html#id1
```

2021-03-12 06:20 UTC, ssaru commented on setup.cfg
> +
```suggestion
[pylint]
max-line-length = 120
fail-under = 8

[pylint.messages_control]
disable = C0330, C0326, C0114, C0115, C0116
# C0114 (missing-module-docstring)
# C0115 (missing-class-docstring)
# C0116 (missing-function-docstring)
# refers: https://black.readthedocs.io/en/stable/compatible_configs.html#pylint
```

2021-03-12 06:21 UTC, ssaru commented on setup.cfg
> +# C0116 (missing-function-docstring)
```suggestion
# C0114 (missing-module-docstring)
# C0115 (missing-class-docstring)
# C0116 (missing-function-docstring)
# referes: https://black.readthedocs.io/en/stable/compatible_configs.html#pylint
```

2021-03-12 06:22 UTC, ssaru commented on setup.cfg
> +ignore_missing_imports = True
```suggestion
ignore_missing_imports = True
# refers: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library
```

2021-03-12 06:24 UTC, ssaru requested changes
@aisolab 리뷰 완료했습니다.

2021-03-13 01:19 UTC, dreamgonfly commented
> > pyproject.toml을 setup.cfg로 교체
> > 이 과정에서 black 대신 brunette를 사용함.
> 
> preferred format인 toml 대신 setup.cfg를 하신 이유가 혹시 무엇일까요? toml로는 할 수 없는 기능이 있는지 궁금합니다!

https://github.com/pretraining/template/issues/34 에 있는 설명 이해했습니다!

2021-03-13 01:19 UTC, aisolab commented on .pre-commit-config.yaml
> +      - id: flake8
눈뜨고다니세요. (toxic)

2021-03-13 01:25 UTC, aisolab commented on .pre-commit-config.yaml
> +  - repo: local
@ssaru 눈을 제대로 뜨셨네요.

2021-03-13 02:01 UTC, ssaru approved these changes

2021-03-13 02:01 UTC, alxiom approved these changes

2021-03-13 02:01 UTC, merged