[python] feat: Pytest, pylint, pipreqs 셋팅
pretraining/template pull request #48
Opened 2021-03-13 15:24 UTC by ssaru

`pre-commit-config.yaml`파일이 그렇게 적힌데는 이유가 다 있을진데,,, 선지자의 깊은 뜻을 헤아리지 못했던
어리석음을 반성합니다. 🤦‍♂️

- pytest, pylint, pipreqs를 이용해서 모든 pre-commit 작동을 remote repo
  를 활용하고자함이 주 목적
    - pytest, pylint, pipreqs를 remote repo로 활용하는 것은 불가능
    - pytest는 pre-commit을 현재 지원하지 않음
    - pylint는 격리된 가상환경 문제와 의존성 패키지 인식 문제로 인하여
      import된 package가 식별이 되지 않아 E401, E0801 에러 발생
    - pipreqs는 현재 유지보수가 되고있지 않으며, pre-commit 지원 안함
      또한, pre-commit이 실행되는 환경은 격리된 환경이라 pipreqs로
      버전을 포함한 의존성 패키지를 추출하는 것이 불가능함

- 위의 사항을 확인하고, 기작성된 내용을 보강하는 방향으로 작업을 진행
    1. `.pre-commit-config.yaml`에 requirements.txt 설치 기술
    2. `.pre-commit-config.yaml`에 pytest 환경 기술
    3. `.pre-commit-config.yaml`에 pytest, pylint 문제점 주석으로 기술
    4. `.pre-commit-config.yaml`변경에 따른 `Makefile` 수정
    5. `Makefile`에 pipreqs, test command 적용
    6. test 코드에 의존성 패키지 테스트 코드 추가

Refs: #42

2021-03-13 23:54 UTC, aisolab commented on Makefile
> +	py.test -o log_cli=true -n 1 --cov-report term-missing tests/
`py.test`라고 쓰는 것과 `pytest`라고 쓰는 것에는 어떤 차이가 있나요?

2021-03-14 00:01 UTC, aisolab requested changes

2021-03-14 00:01 UTC, aisolab commented on Makefile
> +
```suggestion
set-all:
    make set-git
    make set-pre-commit
    make set-tests
    make sete-pipreqs
```
를 추가하는게 어떨까요?

@pretraining/authors

2021-03-14 08:47 UTC, ssaru commented on .pre-commit-config.yaml
> +        entry: pip3 install pytest==6.2.1 pytest-cov==2.10.1 pytest_xdist==2.2.0 pylint==2.7.2
오 좋습니다.
감사합니다.

2021-03-14 08:50 UTC, ssaru commented on Makefile
> +
저는 좋습니다. `set-all`을 해도 되구요

Makefile 상단에 `all: set-git set-pre-commit set-tests set-pipreqs` 을 기술해두면,
그냥 make하나도 모두 동작하게 됩니다.

2021-03-14 08:53 UTC, ssaru commented on Makefile
> +	py.test -o log_cli=true -n 1 --cov-report term-missing tests/
pytest < 3.0 이전에 쓰던 명령어가 `py.test`이구요.
pytest >= 3.0이전에 권장되는 명령어가 `pytest`라는군요.

pytest로 쓰는 것을 권장하므로, 변경하도록 하겠습니다.

refer: https://stackoverflow.com/questions/39495429/py-test-vs-pytest-command

2021-03-14 09:11 UTC, aisolab commented on Makefile
> +
@ssaru 네 해주세요!

2021-03-14 09:17 UTC, bzantium commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
+ pre-commit에 package 설치 명령어를 넣게되면 매 commit 마다 실행되는 것이 아닌가요? 
+ conda 가상환경을 사용할 경우 pip3로 사용할 경우 자칫 global environment에 설치될 수도 있다고 하는데, pip로 하는 것이 더 좋지 않을까요?

2021-03-14 12:05 UTC, Taekyoon commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
저도 같은 의견입니다. 이 명령어를 실행할 때는 프로젝트 환경이 맞게 설정되어있을때 실행해야할 것 같습니다.

2021-03-14 14:54 UTC, ssaru commented on Makefile
> +
이 부분에 대해서 더 고민해보았는데요. `set-all`은 `dev-env`와 같은 내용인 것 같습니다.

`dev-env`로 했을 때, 명령어는 `make dev-env`가 되어서, 개발 환경을 셋팅하는구나라고 이해할 수 있을 것 같은데요,,
`set-all`로 하면, `all`이라는 단어가 어떤 의미를 주는지 애매할 것 같습니다.
실제로 `set-all`을 한다고해서, `Makefile`에 기술된 모든 동작을 셋팅하진 않는 것 같구요.

2021-03-14 14:57 UTC, ssaru commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
의존성 패키지는 `pytest`와 `pylint` 때문에 사용한 것인데,
`pytest`와 `pylint`를 local에서 사용하기 때문에 불필요한 것 같습니다. 
(실험 결과, install-requirements hook이 없어도 잘 동작하였으며, 개발환경에서 dumpy 패키지를 삭제한 결과 테스트가 실패함을 확인할 수 있었습니다.)

해당 실험에 따라, `install-requirements hook`을 제거하도록 할까합니다.

2021-03-14 23:30 UTC, aisolab commented on Makefile
> +
`pipreqs`는 오타가 있는데 그부분 제외하면 모두 동작하지 않나요?

2021-03-14 23:30 UTC, aisolab commented on .pre-commit-config.yaml
> +        entry: pip3 install pytest==6.2.1 pytest-cov==2.10.1 pytest_xdist==2.2.0 pylint==2.7.2
안바뀐것 같은데 혹시 바뀐걸까요?

2021-03-15 00:42 UTC, bzantium commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
동의합니다 :) 수고 많으셨습니다!

2021-03-15 01:04 UTC, Taekyoon commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
저도 동의합니다! 고생하셨습니다!

2021-03-15 01:24 UTC, aisolab commented on .pre-commit-config.yaml
> +        entry: pip3 install -r requirements.txt
@ssaru 논의된 사항 반영후 approved되면 바로 merge해주세요. 좀 지연되네요.

2021-03-15 02:01 UTC, ssaru commented on Makefile
> +
`all`에 반영하였습니다!

2021-03-15 02:12 UTC, bzantium approved these changes
LGTM

2021-03-15 02:27 UTC, aisolab approved these changes
LGTM

2021-03-15 02:34 UTC, merged

2021-03-15 03:19 UTC, Taekyoon commented
LGTM